name = "ZeroRuntime"
version = "0.1.0"
type = "exec"
language = "cpp"

[sources]
dirs = ["src"]

[includes]
dirs = ["include", "../ZeroEngine/include"]

[build]
flags = ["-Wall", "-Wextra", "-Wpedantic"]
optimization = "2"

# Link the static engine library directly and also link raylib
libs = ["raylib"]


# If you use any additional lib dirs (optional for system libs)
lib_dirs = []

[deps]

[scripts]
# prebuild = "echo 'Running prebuild'"
# postbuild = "echo 'Build complete'"
